name: weather_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: IranSansMobile
      fonts:
        - asset: assets/fonts/iran_sans/IranSansMobileFaNum_UltraLight.ttf
          weight: 300
        - asset: assets/fonts/iran_sans/IranSansMobileFaNum_Light.ttf
          weight: 400
        - asset: assets/fonts/iran_sans/IranSansMobileFaNum_Medium.ttf
          weight: 500
        - asset: assets/fonts/iran_sans/IranSansMobileFaNum_Bold.ttf
          weight: 600
        - asset: assets/fonts/iran_sans/IranSansMobileFaNum_Black.ttf
          weight: 700

  # Assets: consist of icons and images
  assets:
    # :: Icons
    - assets/icons/remix_settings.png
    - assets/icons/remix_menu.png
    - assets/icons/remix_map_pin.png
    - assets/icons/remix_leaf.png
    - assets/icons/remix_left_arrow.png
    - assets/icons/remix_right_arrow.png
    - assets/icons/remix_wind.png
    - assets/icons/remix_showers.png
    - assets/icons/remix_drop.png
    - assets/icons/remix_search.png
    - assets/icons/remix_location.png
    - assets/icons/remix_close_fill.png
    - assets/icons/remix_arrow_down_fill.png
    - assets/icons/remix_add_fill.png
    - assets/icons/remix_cloudy_fill.png
    - assets/icons/remix_cloudy_line.png
    - assets/icons/remix_compass.png
    - assets/icons/remix_delete_bin_fill.png
    - assets/icons/remix_sun_line.png
    - assets/icons/remix_temperature_hot_line.png
    - assets/icons/remix_sunrise_line.png
    - assets/icons/remix_sunset_line.png
    - assets/icons/remix_eye_line.png
    - assets/icons/remix_pressure_line.png
    - assets/icons/remix_alert_line.png
    - assets/icons/remix_check_double_line.png
    - assets/icons/remix_close_circle_line.png
    - assets/icons/remix_information_line.png
    - assets/icons/remix_dribbble_line.png
    - assets/icons/remix_github_fill.png
    - assets/icons/remix_instagram_fill.png
    - assets/icons/remix_arrow_down_circle_line.png
    - assets/icons/remix_rocket_line.png
    # :: Images
    # :::: Piqo weather icons
    - assets/images/piqo_weather_icons/day_cloudy.png
    - assets/images/piqo_weather_icons/day_cloudy_showers.png
    - assets/images/piqo_weather_icons/day_cloudy_snow.png
    - assets/images/piqo_weather_icons/day_cloudy_thunder.png
    - assets/images/piqo_weather_icons/day_dreary.png
    - assets/images/piqo_weather_icons/day_flurries.png
    - assets/images/piqo_weather_icons/day_fog.png
    - assets/images/piqo_weather_icons/day_freezing_rain.png
    - assets/images/piqo_weather_icons/day_rain.png
    - assets/images/piqo_weather_icons/day_rainy_snowy.png
    - assets/images/piqo_weather_icons/day_showers.png
    - assets/images/piqo_weather_icons/day_sleet.png
    - assets/images/piqo_weather_icons/day_snow.png
    - assets/images/piqo_weather_icons/day_sun.png
    - assets/images/piqo_weather_icons/day_sun_flurries.png
    - assets/images/piqo_weather_icons/day_sun_hazy.png
    - assets/images/piqo_weather_icons/day_sun_windy.png
    - assets/images/piqo_weather_icons/day_thunder.png
    - assets/images/piqo_weather_icons/night_clear.png
    - assets/images/piqo_weather_icons/night_cloudy.png
    - assets/images/piqo_weather_icons/night_cloudy_flurries.png
    - assets/images/piqo_weather_icons/night_cloudy_showers.png
    - assets/images/piqo_weather_icons/night_cloudy_snow.png
    - assets/images/piqo_weather_icons/night_cloudy_thunder.png
    - assets/images/piqo_weather_icons/night_moon_hazy.png
    - assets/images/piqo_weather_icons/unknown_weather_icon.png
    # :::: Free images
    - assets/images/free_images/light_empty_list.png
    - assets/images/free_images/light_not_found.png
    - assets/images/free_images/dark_empty_list.png
    - assets/images/free_images/dark_not_found.png
    - assets/images/free_images/amsterdam.png
    - assets/images/free_images/crying_face.png
    - assets/images/free_images/relieved_face.png
    - assets/images/free_images/smiling_face.png
    - assets/images/free_images/tired_face.png
    - assets/images/free_images/unamused_face.png
    
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
